[package]
name = "zed_opentofu"
version = "0.1.3"
edition = "2021"
publish = false
license = "Apache-2.0"

[lib]
path = "src/opentofu.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.6.0"
